adev-shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('allauth.urls')),
    path('',include('core.urls'))
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
  

core/urls.py
from django.urls import path,include

from .views import Home,DetailItem,Cart,Update_Cart,Remove_from_cart,Coupon_add,Checkout,Billing_Adress,Payment_stripe,Payment_paypal,about_us,contact_us,Your_Orders,Remove_Order


app_name='core'

urlpatterns = [
  path('',Home,name='home'),
  path('about-us/',about_us,name="about_us"),
  path('contact-us/',contact_us,name="contact_us"),
  path('orders/',Your_Orders,name="your_orders"),
  path('detail/<int:pk>/',DetailItem,name='detail_item'),
  path('cart/',Cart,name="cart"),
  path('update/cart/',Update_Cart,name="update_cart"),
  path('remove/fromcart/<int:pk>',Remove_from_cart,name="remove_from_cart"),
  path('remove/order/<int:pk>',Remove_Order,name='remove_order'),
  path('add/coupon/',Coupon_add, name="coupon"),
  path('checkout/',Checkout,name="checkout"),
  path('order/payment/stripe/',Payment_stripe,name="stripe"),
  path('billing_adress/',Billing_Adress,name="adress"),
  path('order/payment/paypal/',Payment_paypal,name="paypal"),
  


]

core/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.conf import settings
from django_countries.fields import CountryField
# Create your models here.
# variables 
COLOR=(
        ('#800080','PURPLE'),
        ('#ff0000','RED'),
        ('#008000','GREEN'),
        ('#000000','BLACK'),
        ('#f2f2f2','WHITE')

    )

SIZE=(
        ('S','SMALL'),
        ('M','MEDIUM'),
        ('L','LARGE'),
        ('XL','XLARGE')
    )

class Item(models.Model):
  

    title=models.CharField(max_length=50)
    price=models.IntegerField()
    previous_price=models.IntegerField(blank=True,null=True)
    description=models.TextField()
    image_core=models.ImageField(default=False)
    color_core_default=models.CharField(max_length=100,choices=COLOR)
    size_core_default=models.CharField(max_length=100,choices=SIZE)
    color_disponnible=MultiSelectField(max_length=100,choices=COLOR)
    size_disponnible=MultiSelectField(max_length=10,choices=SIZE)

    objects=models.Manager()
    def __str__(self):
        return self.title


class Imagedetail(models.Model):
    item=models.ForeignKey(Item,on_delete=models.CASCADE,blank=True,null=True)
    image=models.ImageField(default=False)
    color_secondary=models.CharField(max_length=100,choices=COLOR)
    
    
    objects=models.Manager()


class OrderItem(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    size=models.CharField(max_length=10,default=True)
    color=models.CharField(max_length=100,default=True)
    quantity=models.IntegerField(default=1)
    is_ordered=models.BooleanField(default=False)


    objects=models.Manager()
    def __str__(self):
        return self.item.title
    
    def get_total(self):
        return self.quantity * self.item.price

    


class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    order_items=models.ManyToManyField(OrderItem)
    is_ordered=models.BooleanField(default=False)
    date_creation=models.DateTimeField()
    coupon=models.ManyToManyField('Coupon')
    adress=models.OneToOneField('BillingAdress',on_delete=models.SET_NULL,blank=True,null=True)
    payment=models.ForeignKey('Payment',on_delete=models.SET_NULL,blank=True,null=True)
  


    def __str__(self):
        return self.user.username

    def get_subtotal(self):
        subtotal=0
        for item in self.order_items.all():
            subtotal+=item.get_total()
        return subtotal

    def get_total(self):
        total=self.get_subtotal()
        for coupon in self.coupon.all():
            total-=coupon.amount
        return total
            


class Coupon(models.Model):
    coupon=models.CharField(max_length=10)
    amount=models.IntegerField()
    expiration=models.BooleanField(default=False)
    minimal_amount_required=models.IntegerField()
    
    def __str__(self):
        return self.coupon
    


class BillingAdress(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,blank=True,null=True)
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    adress1=models.CharField(max_length=200)
    adress2=models.CharField(max_length=200,default=None)
    city=models.CharField(max_length=50)
    zip=models.IntegerField()
    phone=models.IntegerField()
    country=CountryField(multiple=False)
    

class Payment(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,blank=True,null=True)
    stripe_id_charge=models.CharField(max_length=30)
    amount=models.FloatField()
    date_payment=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username 
    

core/forms.py
from django import forms
from django_countries.fields import CountryField
class add_to_cart(forms.Form):
    size=forms.CharField(max_length=10)
    color=forms.CharField(max_length=100)
    quantity=forms.IntegerField()

class billing_adress(forms.Form):
    first_name=forms.CharField(max_length=100,)
    last_name=forms.CharField(max_length=100,)
    adress1=forms.CharField(max_length=200,)
    adress2=forms.CharField(max_length=200,)
    city=forms.CharField(max_length=50,)
    zip=forms.IntegerField()
    phone=forms.IntegerField()
    country=CountryField(blank_label='(select country)').formfield()
    

core/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .models import Item,Imagedetail,OrderItem,Order,Coupon,BillingAdress,Payment
from django.views.generic import ListView,DetailView
from .forms import add_to_cart,billing_adress
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.conf import settings
from django.core.paginator import Paginator
from django.core.mail import send_mail

# Create your views here.
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

# class Home(ListView):
#     model=Item
#     template_name="core/home.html"
#     context_object_name="items"
#     paginate_by=2

def Home(request):
    item=Item.objects.all()
    
    paginator = Paginator(item, 8) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={"page_obj":page_obj}

    if request.user.is_authenticated:
        order=Order.objects.filter(user=request.user,is_ordered=False)
        if order.exists():
            order_qs=order[0]
            context.update({'order':order_qs})
    return render(request,'core/home.html',context)

def about_us(request):
    context={}
    if request.user.is_authenticated:
            
            order=Order.objects.filter(user=request.user,is_ordered=False)
            if order.exists():
                order_qs=order[0]
                context={'order':order_qs}
    return render(request,'core/about-us.html',context)


def contact_us(request):
    context={}
    if request.method=="GET":
        if request.user.is_authenticated:
            
            order=Order.objects.filter(user=request.user,is_ordered=False)
            if order.exists():
                order_qs=order[0]
                context={'order':order_qs}

        return render(request,'core/contact-us.html',context)  

    if request.method=="POST":
        subject=request.POST['subject']
        email_client=request.POST['email']
        message=request.POST['message']
        send_mail(subject,message,email_client,recipient_list=['adev.off@gmail.com'],fail_silently=False)
        messages.info(request,'Thanks for your Feedback')
        return redirect('core:contact_us')


def Your_Orders(request):
    orders_qs=Order.objects.filter(user=request.user)
    print(orders_qs)
  

    context={'orders':orders_qs}
    return render(request,'core/orders.html',context)



def DetailItem(request,pk):
    item=Item.objects.get(pk=pk)
    
    if request.method =="GET":
        context={'item':item}

        if request.user.is_authenticated:
            order=Order.objects.filter(user=request.user,is_ordered=False)
            if order.exists():
                order_qs=order[0]
                context.update({'order':order_qs})
        return render(request,'core/detail_item.html',context)

    if request.method=='POST':
        if request.user.is_authenticated:
            
            
            form=add_to_cart(data=request.POST)
            #create order
            order_qs=Order.objects.filter(user=request.user,is_ordered=False)
            #retourne un query set <queryset [<oder:adev>]> donc pour avoir adev , on doit ajouter [0] 
            if form.is_valid():
                item=Item.objects.get(pk=pk)
                color=form.cleaned_data['color']
                size=form.cleaned_data['size']
                quantity=form.cleaned_data.get('quantity')
                Order_item=OrderItem(user=request.user,item=item,size=size,color=color,quantity=quantity)
                Order_item.save()
                if order_qs.exists():
                    order=order_qs[0]


                    order.order_items.add(Order_item)

                    messages.success(request,"Your order has been created ")
                        #add order in the cart

                        #redirect them to the checkout form
                    return redirect('core:detail_item' ,pk)
                else:
                    order_new=Order.objects.create(user=request.user,date_creation=timezone.now())
                    order_new.save()

                    order_new.order_items.add(Order_item)
        
      
        else:
            messages.info(request,'Sorry you have to sign in First')
            return redirect('/login/')
        
    return redirect('core:detail_item',pk)

@login_required(login_url="/login/")
def Cart(request):
    context={}
    order_item=OrderItem.objects.filter(user=request.user,is_ordered=False)
    

   
        
    
        
        
    
    
    
    if request.method=="GET":

        if request.user.is_authenticated:
            
            order=Order.objects.filter(user=request.user,is_ordered=False)
            if order.exists():
                order_qs=order[0]
                context={'order':order_qs}
        
        return render(request,'core/cart.html',context)

    if request.method=="POST":
        return redirect("core:checkout")

    


@login_required(login_url="/login/")
def Update_Cart(request):
    item_order=OrderItem.objects.filter(user=request.user,is_ordered=False)
    order=Order.objects
    i=1
    for item_qs in item_order:
        input_name="quantity"+str(i)
        item_qs.quantity=request.POST[input_name]
        item_qs.save()
        i+=1
    return redirect('core:cart')

@login_required(login_url="/login/")
def Remove_from_cart(request,pk):
    item_order=get_object_or_404(OrderItem, pk=pk,user=request.user)
    item_order.delete()

    messages.warning(request,"Your item has been Deleted !")
    return redirect('core:cart')




@login_required(login_url="/login/")
def Coupon_add(request):
    coupon_code=request.POST['coupon_code']
    coupon_disponnible=Coupon.objects.filter(expiration=False,coupon=coupon_code)
    if coupon_disponnible.exists():
        coupon=coupon_disponnible[0]
        order_qs=Order.objects.get(user=request.user,is_ordered=False)
        if order_qs.get_total() >= coupon.minimal_amount_required:
            order_qs.coupon.add(coupon)
            coupon.expiration=True
            coupon.save()
            messages.success(request,"your coupon has been added")
            return redirect('core:cart')
        else:
            messages.info(request,"sorry this coupon required $" + str(coupon.minimal_amount_required) +" of minimal amount , Add some Order items to use it !!")
            return redirect('core:cart')
       

    else:
        messages.warning(request,"This coupon doesn't exist, please try again !")
        return redirect('core:cart')


    
    

@login_required(login_url="/login/")
def Checkout(request):
    form=billing_adress()
    context={'form':form}
    order=Order.objects.filter(user=request.user,is_ordered=False)


    if request.user.is_authenticated:
        if order.exists():
            order_qs=order[0]
            context.update({'order':order_qs})
    if order.exists():
       context.update({'order':order[0]})
    if request.method=="GET":

        return render(request,'core/checkout.html',context)

    

@login_required(login_url="/login/")
def Payment_stripe(request):
    order=Order.objects.get(user=request.user,is_ordered=False)
    if order.adress is None:
        messages.info(request,"please Submit Your Billing Adress first !")
        return redirect('core:checkout')
    else:

    
        try:
            token=request.POST['stripeToken']
            #creer une charge
            charge = stripe.Charge.create(
            amount=int(order.get_total())*100, #per cent 
            currency="usd",
            description="My First Test Charge (created for API docs)",
            source=token, # obtained with Stripe.js
            )

            payment=Payment(user=request.user,stripe_id_charge=charge['id'],amount=order.get_total(),date_payment=timezone.now())
            payment.save()
            order.payment=payment
            order.is_ordered=True
            order.save()

            # change is_ordered from false to true
            for items in order.order_items.all():
                items.is_ordered=True
                items.save()
            messages.success(request,"your order has been done !")
            return redirect('core:home')

            
        except stripe.error.CardError as e:
            messages.warning(request,"Card error")
            return redirect('core:checkout')

        except stripe.error.RateLimitError as e:
            messages.warning(request,"RateLimitError")
            return redirect('core:checkout')
        except stripe.error.InvalidRequestError as e:
            messages.warning(request,"InvalidRequestError")
            return redirect('core:checkout')
        except stripe.error.AuthenticationError as e:
            messages.warning(request,"AuthenticationError")
            return redirect('core:checkout')
        except stripe.error.APIConnectionError as e:
            messages.warning(request,"APIConnectionError")
            return redirect('core:checkout')
        except stripe.error.StripeError as e:
            messages.warning(request,"StripeError")
            return redirect('core:checkout')
        except Exception as e:
            messages.warning(request,"error ! Try again please !")
            return redirect('core:checkout')
        



def Payment_paypal(request):
    pass





def Billing_Adress(request):
    order=Order.objects.filter(user=request.user,is_ordered=False)
    form=billing_adress(request.POST)
    if form.is_valid():
        order_qs=order[0]
        first_name=form.cleaned_data['first_name']
        last_name=form.cleaned_data['last_name']
        adress1=form.cleaned_data['adress1']
        adress2=form.cleaned_data['adress2']
        city=form.cleaned_data['city']

templates/core/contact-us.html
{% extends 'base.html' %}

{% block content %}
 <!-- breadcrumb start -->
            <div class="breadcrumb-area">
                <div class="container-fluid text-center">
                    <div class="breadcrumb-stye gray-bg ptb-100">
                        <h2 class="page-title">contact us</h2>
                        <ul>
                            <li><a href="#">home</a></li>
                            <li class="active">contact us</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- breadcrumb end -->
            <!-- contact-area start -->
            <div class="contact-area ptb-100">
                <div class="container-fluid map-contact">
                    <div class="row">
                        <div class="col-lg-7 col-md-7 col-sm-12 text-center">
                            <div class="contact-from gray-bg">
                                <form id="contact-form"  method="post">
                                {% csrf_token %}
                                    <input name="subject" type="text" placeholder="Subject">
                                    <input name="email" type="email" placeholder="Email">
                                    <textarea name="message" placeholder="Your message"></textarea>
                                    <button class="submit" type="submit">Send Message</button>
                                </form>
                                <p class="form-messege"></p>
                            </div>
                        </div>
                        <div class="col-lg-5 col-md-5 col-sm-12">
                            <div class="communication contact-from">
                                <div class="single-communication">
                                    <div class="communication-icon">
                                        <i class="fa fa-home" aria-hidden="true"></i>
                                    </div>
                                    <div class="communication-text">
                                        <h3>Address:</h3>
                                        <p>Hay Lalla Meryem Bloc D Benslimane  </p>
                                    </div>
                                </div>
                                <div class="single-communication">
                                    <div class="communication-icon">
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                    </div>
                                    <div class="communication-text">
                                        <h3>Phone:</h3>
                                        <p>+212636686670</p>
                                    </div>
                                </div>
                                <div class="single-communication">
                                    <div class="communication-icon">
                                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                    </div>
                                    <div class="communication-text">
                                        <h3>Email:</h3>
                                        <p>adev.off@gmail.com</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<iframe width="100%" src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d15068.60996916089!2d-7.133679793239112!3d33.62312832620677!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sma!4v1589377098441!5m2!1sfr!2sma" width="1644" height="500" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>


{% endblock content %}

templates/core/detail_item.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/detail_items.css' %}" >
{% endblock style %}

{% block content %}




            <!-- breadcrumb start -->
            <div class="breadcrumb-area">
                <div class="container-fluid text-center">
                    <div class="breadcrumb-stye gray-bg ptb-100">
                        <h2 class="page-title">product details</h2>
                        <ul>
                            <li><a href="{% url 'core:home' %}">home</a></li>
                            <li class="active">product details</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- breadcrumb end -->
            <!-- page section start -->
            <div class="page-section section ptb-100">
                <div class="container-fluid">
                    <div class="row mb-40">
                        <!-- QuickView Product Images -->
    
                        <div class="col-md-5 col-sm-6 col-xs-12 mb-40">	
                            <!-- Tab panes -->
                            <div class="tab-content mb-10">
                                <div class="pro-large-img tab-pane active" >
                                    <img src="{% static "assets/img/shop/2.jpg" %}" alt="" />
                                </div>
                                {% for images in item.imagedetail_set.all %}
                                <div class="pro-large-img tab-pane" id="{{images.pk}}">
                                    <img src="{% static "assets/img/shop/2.jpg" %}" alt="" />
                                </div>
                                {% endfor %}
                              
                            </div>
                            <!-- QuickView Product Thumbnail Slider -->
                            <div class="pro-thumb-img-slider">
                            {% for images in item.imagedetail_set.all %}
                                <div><a href="#{{images.pk}}" onclick="myfunction({{images.pk}})" data-toggle="tab"><img src="{% static "assets/img/shop/2.jpg" %}" alt="" /></a></div>
                             {% endfor %}
                             
                            </div>
                        </div>
                        <!-- QuickView Product Details -->
                        <div class="col-md-7 col-sm-6 col-xs-12 mb-40">
                            <div class="product-details section">
                                <!-- Title -->
                                <h1 class="title">{{item.title}}</h1>
                                <!-- Price Ratting -->
                                <div class="price-ratting section">
                                    <!-- Price -->
                                    <span class="price float-left"><span class="new">$ {{item.price}}</span></span>
                                    <!-- Ratting -->
                                    <span class="ratting float-right">
                                        <i class="fa fa-star active"></i>
                                        <i class="fa fa-star active"></i>
                                        <i class="fa fa-star active"></i>
                                        <i class="fa fa-star active"></i>
                                        <i class="fa fa-star active"></i>
                                        <span> (01 Customer Review)</span>
                                    </span>
                                </div>
                                <!-- Short Description -->
                                <div class="short-desc section">
                                    <h5 class="pd-sub-title">Quick Overview</h5>
                                    <p>{{item.description}}</p>
                                </div>
                                <!-- Product Size -->
                        <form action="" method='post' >
                        {% csrf_token %}
                                <div class="product-size section">
                                    <h5 class="pd-sub-title">Select Size:<strong class="default_size">   {{item.size_core_default}} </strong> </h5>

                                    <input name="size" type="hidden" id="size" value="{{item.size_core_default}}" >

                                    {% for size in item.size_disponnible %}
 <button   type="button" class="size_disponnible" onclick="size_function('{{size}}')">{{size}}
                                    </button>
                                    


                                    {% comment %} <button   type="button" class="size_disponnible" onclick="size_function({{size}})">{{size}}
                                               <input class="size"  id="{{size}}"  value="{{size}}" type="text" >
                                    </button> {% endcomment %}
                                    {% endfor %}
                                   

                                   
                                    
                                </div>
                                
                                <!-- Product Color -->
                                <div class="color-list section">
                                <h5 class="pd-sub-title">Select Color:    <strong class="default_color"> {{item.get_color_core_default_display}} </strong> </h5>
                                <input name="color" type="hidden" id="color" value="{{item.get_color_core_default_display}}">
                                    {% for images in item.imagedetail_set.all %}

                                     <a href="#{{images.pk}}" data-toggle="tab" ><button  class=" color_disponnible" id="color{{images.pk}}" onclick="color_function('{{images.get_color_secondary_display}}')" style="background-color: {{images.color_secondary}};"><i class="fa fa-check"></i>
                                  
                                     </button></a>
                                    {% endfor %}
                                   		</div>

                                 
                                {% comment %} </div>
                            {% endcomment %}

                                <!-- Quantity Cart -->
                                <div class="quantity-cart section">
                                    <div class="product-quantity2">
                                        <input name="quantity" type="text" value="1">
                                    </div>
                                    <button type="submit" class="add-to-cart">add to cart</button>
                                </div>

                        </form>

                        <!--messages alert -->
                  
                                <!-- Usefull Link -->
                                <ul class="usefull-link section">
                                    <li><a href="#"><i class="pe-7s-mail"></i> Email to a Friend</a></li>
                                    <li><a href="#"><i class="pe-7s-like"></i> Wishlist</a></li>
                                    <li><a onclick='window.print()'><i class="pe-7s-print"></i> print</a></li>
                                </ul>
                                <!-- Share -->
                                <div class="share-icons section">
                                    <span>share :</span>
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-instagram"></i></a>
                                    <a href="#"><i class="fa fa-pinterest"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <!-- Nav tabs -->
                        <div class="col-xs-12">
                            <ul class="pro-info-tab-list section">
                                <li class="active"><a href="#more-info" data-toggle="tab">More info</a></li>
                                <li><a href="#data-sheet" data-toggle="tab">Data sheet</a></li>
                                <li><a href="#reviews" data-toggle="tab">Reviews</a></li>
                            </ul>
                        </div>
                        <!-- Tab panes -->
                        <div class="tab-content col-xs-12">
                            <div class="pro-info-tab tab-pane active" id="more-info">
                                <p>Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!</p>
                            </div>
                            <div class="pro-info-tab tab-pane" id="data-sheet">
                                <table class="table-data-sheet">
                                    <tbody>
                                        <tr class="odd">
                                            <td>Compositions</td>
                                            <td>Cotton</td>
                                        </tr>
                                        <tr class="even">
                                            <td>Styles</td>
                                            <td>Casual</td>
                                        </tr>
                                        <tr class="odd">
                                            <td>Properties</td>
                                            <td>Short Sleeve</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="pro-info-tab tab-pane" id="reviews">
                                <a href="#">Be the first to write your review!</a>
                            </div>
                        </div>		
                    </div>
                </div>
            </div>

            <!-- page section end -->

	
		


  
              {% endblock content %}
        
{% block script %}
<script src="{% static 'assets/js/detail_item.js' %}"></script>
{% endblock script %}
        